# Generated by Django 3.2.16 on 2023-04-28 21:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.IntegerField()),
                ('endereco', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.IntegerField()),
                ('telefone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero', models.IntegerField()),
                ('numero_reclamacao', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('anexo', models.FileField(upload_to='\nanotech')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nanotech.login')),
            ],
        ),
    ]
